---
name: Full CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  full-check:
    name: Full CI Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake build-essential ccache \
          qtbase5-dev libqt5sql5-sqlite libgl1-mesa-dev \
          clang-format cppcheck clang-tidy

      - name: Install LinuxDeploy
        run: |
          # LinuxDeploy
          wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20251107-1/linuxdeploy-x86_64.AppImage
          echo "c20cd71e3a4e3b80c3483cef793cda3f4e990aca14014d23c544ca3ce1270b4d  linuxdeploy-x86_64.AppImage" | sha256sum -c -

          # Qt Plugin
          wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/1-alpha-20250213-1/linuxdeploy-plugin-qt-x86_64.AppImage
          echo "15106be885c1c48a021198e7e1e9a48ce9d02a86dd0a1848f00bdbf3c1c92724  linuxdeploy-plugin-qt-x86_64.AppImage" | sha256sum -c -

          chmod +x linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-plugin-qt-x86_64.AppImage
          sudo mv linuxdeploy-x86_64.AppImage /usr/local/bin/linuxdeploy
          sudo mv linuxdeploy-plugin-qt-x86_64.AppImage /usr/local/bin/linuxdeploy-plugin-qt

      - name: Check Formatting
        run: |
          make format
          git diff
          git diff --stat
          git diff --quiet --exit-code

      - name: Lint
        run: make lint

      - name: Build AppImage
        run: make appimage

      - name: Test
        run: make test

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: nutra-linux-appimage
          path: build/*.AppImage
